USE customer_behaviour;

select * from Customer_Data;

--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as Total_revenue from Customer_Data
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from Customer_Data
where discount_applied = 'Yes' and 
purchase_amount > (select avg(purchase_amount) from Customer_Data)  ;


--Q3. Which are the top 5 products with the highest average review rating?
select top 5  item_purchased, round(avg(review_rating),2) as Avg_review_rating from Customer_Data
group by item_purchased
order by avg(review_rating) desc;

--0R

select item_purchased,avg_review_rating 
from ( 
select item_purchased,avg(review_rating) as avg_review_rating ,
ROW_NUMBER() over(order by avg(review_rating) desc ) as rn 
from Customer_Data
group by item_purchased) t
where rn <= 5;



--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type , avg(purchase_amount) as avg_purchase_amount from Customer_Data
where Shipping_type = 'Standard'  or shipping_type = 'Express'
group by shipping_type;



--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status ,
count(customer_id)as members,
avg(purchase_amount)as avg_revenue,
sum(purchase_amount)as total_revenue 
from Customer_Data
where subscription_status in ('yes','no')
group by subscription_status;



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5  item_purchased ,
100 * sum(case when discount_applied = 'yes' then 1 else 0 end) / count(*) as discount_rate
from Customer_Data
group by item_purchased
order by discount_rate desc;



--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases, 
case when previous_purchases = 1 then 'New'
	 when previous_purchases between 2 and 10 then 'Returning'
	 else 'Loyal'
	 End as customer_segment
from customer_data )
select customer_segment , count(*) AS No_of_customer from customer_type
group by customer_segment
order by No_of_customer desc;

select * from Customer_Data

--Q8. What are the top 3 most purchased products within each category?
with item_count as (
select category , item_purchased , count(customer_id) as total_orders ,
Row_number() over(partition by category ORDER BY COUNT(customer_id) DESC) as item_rank 
from customer_data
group by category , item_purchased )

select  item_rank,category,item_purchased,total_orders from item_count
where item_rank <= 3;




--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers from Customer_Data
where previous_purchases > 5
group by subscription_status



--Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as Revenue from Customer_Data
group by age_group
order by sum(purchase_amount) desc;